title: A-GeoCat
greeting: Welcome to A-GeoCat
description: Alfobre Geodata Catalog
logo: /img/geocat.svg
hero_image: /img/homepage-hero.jpg
strict_front_matter: true
url: https://projetoalfobre.github.io/a-geocat/

# Site theme
jkan_theme: Default

# Dataset schema
schema: geocat

# Nav bar
navigation:
  - title: Data
    url: /datasets/
  - title: Categories
    url: /categories/
  - title: Regions
    url: /regions/
  - title: About Us
    url: /aboutus/    

# Collections
collections:
  datasets:
    output: true
    permalink: /datasets/:path/
  regions:
    output: true
    permalink: /regions/:path/
  dataset_categories:
    output: true
    permalink: /categories/:path/

# Collections (cont'd)
defaults:
  - scope:
      path: ""
      type: dataset_categories
    values:
      layout: category
  - scope:
      path: ""
      type: datasets
    values:
      layout: dataset
      category: Uncategorized
      region: N/A
  - scope:
      path: ""
      type: regions
    values:
      layout: region

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

# Google Analytics
google_analytics:
  enabled: false
  code: "UA-XXXXXX-1"

# US Digital Analytics Program - https://analytics.usa.gov
digital_analytics_program:
  enabled: false
  agency: ""
  subagency: ""

# Hypothesis.io - Annotator
hypothesis:
  enabled: false

# Twitter
twittercard:
  enabled: false
  username: "@"

# Open Graph
opengraph:
  enabled: true

# Plugins
plugins:
  - "jekyll-github-metadata"
  - "jekyll-relative-links"
  - "jekyll-paginate-v2"
  - "jekyll-titles-from-headings"
  - "jekyll-feed"

# Exclude these files from the build
exclude:
  - CONTRIBUTING.md
  - Dockerfile
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - scripts/src
  - package.json
  - package-lock.json
  - README.md
  - LICENSE
  - netlify
  - netlify.toml
  - .parcel-cache
  - docs
